function[Fl] = LaiskFluorescence_backup(Ynames,knames,k,Sol) 

kn = find(strcmp(knames,'kn'));
kp = find(strcmp(knames,'kp'));
kr = find(strcmp(knames,'kr')); 
kq = find(strcmp(knames,'kq')); 

yopoax = find(contains(Ynames,'YoPoA'));
yoprao = find(contains(Ynames,'YoPrAo'));
yoprar = find(contains(Ynames,'YoPrAr'));
yrprao = find(contains(Ynames,'YrPrAo'));
yrprar = find(contains(Ynames,'YrPrAr'));


Fl = 1/(1+k(kn)+k(kr)+k(kq))*(sum(Sol(yopoax,:)))...
     ...
     +1/(1+k(kp)+k(kn)+k(kr))*(sum(Sol(yoprao,:)))...
     ...
     +1/(1+k(kn)+k(kr))*(sum(Sol(yoprar,:)))...
     ...
     +1/(1+k(kp)+k(kn))*(sum(Sol(yrprao)))+...
     ...
     1/(1+k(kn))*(sum(Sol(yrprar)));

end
